In [1]:
include("../src/Categories.jl")

Main.Categories

In [2]:
include("../src/Functors.jl")

Main.Functors

In [3]:
using .Categories

In [4]:
using .Functors

In [5]:
using LinearAlgebra

In [6]:
struct MatC <: Category{Int,AbstractMatrix{Int}}
end

In [7]:
Categories.dom(::MatC, m::AbstractMatrix{Int}) = size(m)[1]

In [8]:
Categories.codom(::MatC, m::AbstractMatrix{Int}) = size(m)[2]

In [9]:
Categories.id(::MatC, n::Int) = I(n)

In [10]:
Categories.compose(::MatC, f::AbstractMatrix{Int}, g::AbstractMatrix{Int}) = f * g

In [11]:
struct FinFunction
    dom::Int
    codom::Int
    values::Vector{Int}
end

In [12]:
struct FinC <: Category{Int, FinFunction}
end

In [13]:
Categories.dom(::FinC, f) = f.dom

In [14]:
Categories.codom(::FinC, f) = f.codom

In [15]:
Categories.compose(::FinC, f::FinFunction, g::FinFunction) = FinFunction(f.dom, g.codom, [g.values[f.values[i]] for i in 1:f.dom])

In [16]:
Categories.id(::FinC, n::Int) = FinFunction(n, n, [i for i in 1:n])

In [17]:
struct F <: Functor{FinC, MatC}
end

In [18]:
Categories.dom(::KittenC, ::F) = FinC()

In [19]:
Categories.codom(::KittenC, ::F) = MatC()

In [20]:
Functors.ob_map(::F, n::Int) = n

In [21]:
function Functors.hom_map(::F, f::FinFunction)
    A = zeros(Int, (f.dom, f.codom))
    for i in 1:f.dom
        A[i,f.values[i]] = 1
    end
    A
end

In [22]:
f = FinFunction(3, 2, [2,1,2])

FinFunction(3, 2, [2, 1, 2])

In [23]:
g = FinFunction(2, 4, [4,2])

FinFunction(2, 4, [4, 2])

In [24]:
compose(FinC(), f, g)

FinFunction(3, 4, [2, 4, 2])

In [25]:
hom_map(F(), compose(FinC(), f, g))

3×4 Matrix{Int64}:
 0  1  0  0
 0  0  0  1
 0  1  0  0

In [26]:
compose(MatC(), hom_map(F(), f), hom_map(F(), g))

3×4 Matrix{Int64}:
 0  1  0  0
 0  0  0  1
 0  1  0  0

In [27]:
hom_map(F(), f)

3×2 Matrix{Int64}:
 0  1
 1  0
 0  1

In [28]:
hom_map(F(), g)

2×4 Matrix{Int64}:
 0  0  0  1
 0  1  0  0